jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # Especifica el entorno donde están los secrets
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
